"""empty message

Revision ID: 9da7ec876fff
Revises: 
Create Date: 2024-08-22 21:11:59.084887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da7ec876fff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_curso', sa.String(length=120), nullable=False),
    sa.Column('duracao', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estudantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=15), nullable=True),
    sa.Column('data_nascimento', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('inscricoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cursos_id', sa.Integer(), nullable=True),
    sa.Column('estudantes_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cursos_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['estudantes_id'], ['estudantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscricoes')
    op.drop_table('estudantes')
    op.drop_table('cursos')
    # ### end Alembic commands ###
